### ISSUE TITLE
"Download" gets cut off on form. 

### ISSUE THREAD

**Issue by fernandalavalle** [m-lab/bq2geojson#120] opened 2016-02-09 17:08 UTC
Using Mac and Chrome 48.0. 
![downloadcutoff](https://cloud.githubusercontent.com/assets/3836867/12923961/c63fa050-cf25-11e5-9d7c-7279d67c0e27.png)

**Comment by gembarrett** [comment] 2016-02-09 17:13
Duplicate of #113

**Closed as completed by gembarrett** 2016-02-09 17:13 UTC
